### ISSUE TITLE
Shadowing variable in case branch may lead to broken javascript code

### ISSUE THREAD

**Issue by keenbug** [elm-lang/elm-compiler#1090]
When you write something like [the following](http://share-elm.com/sprout/5616dc31e4b0966c193dd419)
```elm
foo : Maybe number -> number
foo variableInCase =
  case variableInCase of
    Just n ->
      let
        variableInCase = Just "anything you want"  -- shadow variableInCase used in case
      in
        n  -- which will be used here in the javascript code to extract the field (variableInCase._0)

    _ ->
      0
```
elm will compile the ```n``` in the let body to ```variableInCase._0```, but which has been shadowed and the result is now the string ```"anything you want"```.

Edit: on elm 0.15

**Comment by keenbug** [comment]
Generated code for the example given:
```javascript
   var foo = function (variableInCase) {
      return function () {
         switch (variableInCase.ctor)
         {case "Just":
            return function () {
                 var variableInCase = $Maybe.Just("anything you want");
                 return variableInCase._0;
              }();}
         return 0;
      }();
   };
```

**Comment by evancz** [comment]
Looks like the same root issue as #1086. I'm currently working on a fix to that, so both should get fixed at once.

**Comment by evancz** [comment]
Thanks for the report, just fixed it. This should be out with 0.16 which is coming soon!

**Comment by jvoigtlaender** [comment]
The problem here wasn't really solved, it seems to me. Success was declared because

https://github.com/elm-lang/elm-compiler/blob/master/tests/test-files/good/CodeGenBugs/Shadowing2.elm

now compiles to

https://github.com/elm-lang/elm-compiler/blob/master/tests/test-files/good-expected-js/CodeGenBugs/Shadowing2.elm.js

But a very simply variation of the former:
```elm
withDefault0 : Maybe Int -> Int
withDefault0 maybe =
  case maybe of
    Just int ->
      let
        maybe =
          Just "shadow argument, but do not overwrite it in JS!"
      in
        int -- should be from the `maybe` in the argument, not the shadow

    _ ->
      0
```
into:
```elm
import Graphics.Element

withDefault0 : Maybe Int -> Int
withDefault0 maybe = identity <|
  case maybe of
    Just int ->
      let
        maybe =
          Just "shadow argument, but do not overwrite it in JS!"
      in
        int -- should be from the `maybe` in the argument, not the shadow

    _ ->
      0

main = Graphics.Element.show (withDefault0 Nothing)
```
still leads to a runtime error, even with Elm 0.16.

See also https://github.com/elm-lang/elm-compiler/issues/1223#issuecomment-169645306.
