### ISSUE TITLE
real time search swallows typed characters

### ISSUE THREAD

**Issue by Dobiasd** [elm-lang/elm-compiler#835]
While I type fast in the [library edit box](http://library.elm-lang.org/catalog/elm-lang-Elm/0.13/), it often seems to ignore some characters I type. For example when typing "string" it only shows "sring".
Or "lst" while typing "list". I can reproduce this behaviour with firefox and chromium.

A quite easy way to reproduce it, is to type "string" slowly, then shift+pos1 (to mark the text) and then type "list" (or something else) quite fast. On my machine the text will not be erased at all in most cases.

**Comment by evancz** [comment]
I am trying to make all the issues here directly about elm-compiler, so I am going to close it here but mention elm-lang/core#332 so it will be easy to find from the relevant repo.

I'm sorry this bug has been in there for so long :(

**Comment by witoldsz** [comment]
This is strange. I though the issue was resolved long time ago. Today I have been playing with Chromium browser and Serenity framework for end-to-end tests. It uses a Selenium WebDriver.
The trouble is, the tests are failing because some letters typed into text fields are "swallowed". Took me some time to figure out why did the tests fail on login so often… There are no issues when using Firefox, though.

Using Elm 0.18, Chromium v.53.0.

**Comment by ThomasLocke** [comment]
This is still an issue with Elm 0.18.

I have an input field that filters a list on input. When typing really fast, some characters simply vanish. The problem seems to be happen a lot less on Firefox, but it does happen.

**Comment by ThomasLocke** [comment]
I solved this issue using ports. Elm no longer manages the troubled input field, and my users can once again type at their regular speed, without losing characters.

It feels like a bit of a hack though. Here's hoping this problem is fixed in 0.19.  :)

**Comment by witoldsz** [comment]
My solution was to replace the `value` with `defaultValue` on the input fields, so the content is set only once and then it does not get updates from model, so it's one way `input`→`model` only.

Works OK until you have some logic which changes the values of those fields from within other actions.
